//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Faturas = new HashSet<Fatura>();
        }
    
        public int Customer_ID { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
    
        public virtual Fatura Fatura { get; set; }
        public virtual ICollection<Fatura> Faturas { get; set; }
    }
}
