//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public Fatura()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Fatura_ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
